version: "3"
services:
  #  app:
  #    build: .
  #    depends_on:
  #      - mongodb
  #    environment:
  #      DATABASE_URL: "${DATABASE_URL}"
  #      SERVER_PORT: "${SERVER_PORT}"
  #
  #    ports:
  #      - "${SERVER_PORT}:${SERVER_PORT}"
  #    command: java -jar ./target/movies-0.0.1-SNAPSHOT.jar
  #    volumes:
  #      - .:/app/
  #      - /app/target

  mongodb:
    image: mongo:latest
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
